// LLM Developer Toolbox Utilities
// JSON Repair, Escape/Unescape, JSON Schema Generator, TypeScript Type Generator, Token Counter

/**
 * Repairs broken JSON strings generated by LLMs (comments, single quotes, trailing commas, unquoted keys, etc.)
 */
export function repairJsonString(text) {
  if (!text || typeof text !== 'string') return text;

  let cleaned = text.trim();

  // Strip Markdown code blocks (e.g. ```json ... ```)
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```[a-zA-Z]*\n?/, '').replace(/\n?```$/, '').trim();
  }

  // Remove single line comments // ... and multi-line comments /* ... */
  cleaned = cleaned.replace(/\/\*[\s\S]*?\*\//g, '');
  cleaned = cleaned.replace(/(^|[^:])\/\/[^\n]*/g, '$1');

  // Replace single quoted keys and values with double quotes
  // Key replacement: 'key': -> "key":
  cleaned = cleaned.replace(/'([^'\\]*(?:\\.[^'\\]*)*)'\s*:/g, '"$1":');

  // Replace single quoted string values: : 'value' -> : "value"
  cleaned = cleaned.replace(/:\s*'([^'\\]*(?:\\.[^'\\]*)*)'/g, ': "$1"');

  // Fix unquoted object keys: { key: "val" } -> { "key": "val" }
  cleaned = cleaned.replace(/([{,]\s*)([a-zA-Z0-9_$]+)\s*:/g, '$1"$2":');

  // Remove trailing commas before } or ]
  cleaned = cleaned.replace(/,\s*([}\]])/g, '$1');

  // Replace Python/JS literals (None -> null, True -> true, False -> false, undefined -> null)
  cleaned = cleaned.replace(/\bNone\b/g, 'null');
  cleaned = cleaned.replace(/\bTrue\b/g, 'true');
  cleaned = cleaned.replace(/\bFalse\b/g, 'false');
  cleaned = cleaned.replace(/\bundefined\b/g, 'null');
  cleaned = cleaned.replace(/\bNaN\b/g, 'null');

  // Auto-close missing brackets / braces if truncated by token limits
  let openBraces = 0;
  let openBrackets = 0;
  let inString = false;
  let isEscaped = false;

  for (let i = 0; i < cleaned.length; i++) {
    const char = cleaned[i];
    if (isEscaped) {
      isEscaped = false;
      continue;
    }
    if (char === '\\') {
      isEscaped = true;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      continue;
    }
    if (!inString) {
      if (char === '{') openBraces++;
      if (char === '}') openBraces = Math.max(0, openBraces - 1);
      if (char === '[') openBrackets++;
      if (char === ']') openBrackets = Math.max(0, openBrackets - 1);
    }
  }

  // Close unclosed string if string was cut off
  if (inString) {
    cleaned += '"';
  }

  // Remove trailing comma if present at end of string
  cleaned = cleaned.replace(/,\s*$/, '');

  // Append missing closing braces/brackets
  while (openBraces > 0 || openBrackets > 0) {
    if (openBrackets > 0 && (openBraces === 0 || cleaned.lastIndexOf('[') > cleaned.lastIndexOf('{'))) {
      cleaned += ']';
      openBrackets--;
    } else if (openBraces > 0) {
      cleaned += '}';
      openBraces--;
    }
  }

  return cleaned;
}

/**
 * Escapes JSON text for insertion into LLM prompts or code strings
 */
export function escapeJsonString(text) {
  if (typeof text !== 'string') {
    text = JSON.stringify(text, null, 2);
  }
  return JSON.stringify(text);
}

/**
 * Unescapes an escaped JSON string or wrapped JSON string
 */
export function unescapeJsonString(text) {
  if (!text || typeof text !== 'string') return text;
  let trimmed = text.trim();

  // If wrapped in double quotes as a JSON string, parse it once
  if ((trimmed.startsWith('"') && trimmed.endsWith('"')) || (trimmed.startsWith("'") && trimmed.endsWith("'"))) {
    try {
      const parsed = JSON.parse(trimmed);
      if (typeof parsed === 'string') {
        trimmed = parsed;
      }
    } catch {
      // Manual unescape fallback
      trimmed = trimmed.substring(1, trimmed.length - 1);
    }
  }

  // Replace common escape sequences
  trimmed = trimmed
    .replace(/\\"/g, '"')
    .replace(/\\'/g, "'")
    .replace(/\\\\/g, '\\')
    .replace(/\\n/g, '\n')
    .replace(/\\r/g, '\r')
    .replace(/\\t/g, '\t');

  return trimmed;
}

/**
 * Generates JSON Schema (Draft 7) from JSON object
 */
export function generateJsonSchema(val, title = 'Root') {
  function getType(v) {
    if (v === null) return 'null';
    if (Array.isArray(v)) return 'array';
    return typeof v;
  }

  function parseNode(node, keyName) {
    const type = getType(node);

    if (type === 'object') {
      const properties = {};
      const required = [];
      for (const k of Object.keys(node)) {
        properties[k] = parseNode(node[k], k);
        required.push(k);
      }
      return {
        type: 'object',
        properties,
        ...(required.length > 0 ? { required } : {})
      };
    }

    if (type === 'array') {
      if (node.length === 0) {
        return { type: 'array', items: {} };
      }
      // Infer item schema from first element or merged schema
      const itemSchema = parseNode(node[0], 'item');
      return {
        type: 'array',
        items: itemSchema
      };
    }

    if (type === 'number') {
      return { type: Number.isInteger(node) ? 'integer' : 'number' };
    }

    return { type };
  }

  const rootSchema = parseNode(val, title);
  return JSON.stringify({
    $schema: 'http://json-schema.org/draft-07/schema#',
    title,
    ...rootSchema
  }, null, 2);
}

/**
 * Generates TypeScript Type Definitions from JSON object
 */
export function generateTypeScriptTypes(val, rootName = 'RootObject') {
  const interfaces = [];
  let interfaceCount = 0;

  function toPascalCase(str) {
    return str.replace(/(^\w|-\w|_\w)/g, (m) => m.replace(/[-_]/g, '').toUpperCase());
  }

  function parseNode(node, name) {
    if (node === null) return 'any';
    if (Array.isArray(node)) {
      if (node.length === 0) return 'any[]';
      const itemType = parseNode(node[0], name + 'Item');
      return `${itemType}[]`;
    }
    if (typeof node === 'object') {
      const typeName = interfaceCount === 0 ? rootName : toPascalCase(name);
      interfaceCount++;

      const fields = [];
      for (const [k, v] of Object.entries(node)) {
        const fieldType = parseNode(v, k);
        const validKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : `"${k}"`;
        fields.push(`  ${validKey}: ${fieldType};`);
      }

      interfaces.push(`export interface ${typeName} {\n${fields.join('\n')}\n}`);
      return typeName;
    }

    if (typeof node === 'number') return Number.isInteger(node) ? 'number' : 'number';
    if (typeof node === 'boolean') return 'boolean';
    if (typeof node === 'string') return 'string';

    return 'any';
  }

  parseNode(val, rootName);
  return interfaces.reverse().join('\n\n');
}

/**
 * Estimates LLM Token Count (GPT-4 / Claude heuristic calculation)
 */
export function estimateTokens(text) {
  if (!text) return 0;
  if (typeof text !== 'string') {
    text = JSON.stringify(text);
  }

  // Count English chars, CJK chars, numbers, symbols
  let tokenCount = 0;
  for (let i = 0; i < text.length; i++) {
    const code = text.charCodeAt(i);
    // CJK / Korean / Japanese / Chinese characters take ~1-2 tokens per char
    if ((code >= 0xAC00 && code <= 0xD7A3) || (code >= 0x4E00 && code <= 0x9FFF)) {
      tokenCount += 1.5;
    } else if (code <= 127) {
      tokenCount += 0.28; // ~3.5-4 chars per token for English & JSON symbols
    } else {
      tokenCount += 1;
    }
  }

  return Math.ceil(tokenCount);
}

/**
 * Calculates dataset node counts and byte size metrics
 */
export function calculateDatasetMetrics(data) {
  let nodeCount = 0;
  let keyCount = 0;
  let valueCount = 0;

  function traverse(node) {
    if (node === null || typeof node !== 'object') {
      valueCount++;
      nodeCount++;
      return;
    }

    if (Array.isArray(node)) {
      nodeCount++;
      for (const item of node) {
        traverse(item);
      }
      return;
    }

    nodeCount++;
    for (const [k, v] of Object.entries(node)) {
      keyCount++;
      traverse(v);
    }
  }

  traverse(data);

  const jsonStr = typeof data === 'string' ? data : JSON.stringify(data);
  const byteSize = new Blob([jsonStr]).size;

  let formattedSize = `${byteSize} B`;
  if (byteSize >= 1024 * 1024) {
    formattedSize = `${(byteSize / (1024 * 1024)).toFixed(2)} MB`;
  } else if (byteSize >= 1024) {
    formattedSize = `${(byteSize / 1024).toFixed(1)} KB`;
  }

  return {
    nodeCount,
    keyCount,
    valueCount,
    byteSize,
    formattedSize,
    estimatedTokens: estimateTokens(jsonStr)
  };
}
